spring:
  web:
    resources:
      chain:
        compressed: true
      cache:
        cachecontrol:
          cache-public: true
          max-age: 86400
    locale-resolver: fixed
    locale: pt_BR