name: Deploy to Azure VM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs: 
      deployment_notes: 
        description: "Deployment"
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build application
        run: |
          ./gradlew clean build
          
      - name: Upload application
        uses: appleboy/scp-action@master
        with:       
          host: ${{ secrets.SERVER_IP_ADDRESS }}        
          username: ${{ secrets.SERVER_USERNAME }}      
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 22
          source: "my-app.jar"      
          target: "~/source"
          
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_IP_ADDRESS }}       
          username: ${{ secrets.API_USERNAME }}     
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            sudo /etc/init.d/my-app stop
            mv ~/source/my-app.jar ~/source/my-app-old.jar
            mv ~/source/my-app-latest.jar ~/source/my-app.jar
            sudo rm -rf /etc/init.d/my-app
            sudo ln -s -f ~/source/my-app.jar /etc/init.d/my-app
            sudo /etc/init.d/my-app start
            rm ~/source/my-app-old.jar
